name: Update fake-ip-user.yaml
on:
  workflow_dispatch:
  schedule:
    - cron: "0 19 * * *"
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - ".github/workflows/delete-old-workflows.yml"

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repository
      uses: actions/checkout@main

    - name: Generate geox-user.yaml
      run: |
        echo "update_version=$(date -d '+8 hours' +'%Y-%m-%d')" >> ${GITHUB_ENV}
        mkdir -p ./fake-ip-config/
        rm -f ./fake-ip-config/*
        cat <<EOF > ./fake-ip-config/geox-user.yaml
        dns:
          enable: true
          prefer-h3: true
          ipv6: true
          listen: 0.0.0.0:1053
          fake-ip-range: 198.18.0.1/16
          enhanced-mode: fake-ip
          fake-ip-filter:
        EOF
        curl -sSL https://raw.githubusercontent.com/juewuy/ShellClash/master/public/fake_ip_filter.list | grep -v "#" | sed '/^\s*$/d' | sed "s/.*/'&'/g" | sed 's/^/    - /g' >> ./fake-ip-config/geox-user.yaml
        cat <<EOF >> ./fake-ip-config/geox-user.yaml
            - 'adguardteam.github.io'
            - 'anti-ad.net'
          default-nameserver:
            - https://223.5.5.5/dns-query
            - https://1.12.12.12/dns-query
          nameserver:
            - https://dns.alidns.com/dns-query
            - https://doh.pub/dns-query
          nameserver-policy:
            'geosite:microsoft@cn,apple-cn,google-cn,category-games@cn': [https://doh.pub/dns-query, https://dns.alidns.com/dns-query]
            'geosite:cn,private': [https://doh.pub/dns-query, https://dns.alidns.com/dns-query]
            'geosite:geolocation-!cn': ['https://dns.google/dns-query#🪜 代理域名', 'https://cloudflare-dns.com/dns-query#🪜 代理域名']
        EOF

    - name: Generate ruleset-user.yaml
      run: |
        cat <<EOF > ./fake-ip-config/ruleset-user.yaml
        dns:
          enable: true
          prefer-h3: true
          ipv6: true
          listen: 0.0.0.0:1053
          fake-ip-range: 198.18.0.1/16
          enhanced-mode: fake-ip
          fake-ip-filter:
        EOF
        curl -sSL https://raw.githubusercontent.com/juewuy/ShellClash/master/public/fake_ip_filter.list | grep -v "#" | sed '/^\s*$/d' | sed "s/.*/'&'/g" | sed 's/^/    - /g' >> ./fake-ip-config/ruleset-user.yaml
        cat <<EOF >> ./fake-ip-config/ruleset-user.yaml
            - 'adguardteam.github.io'
            - 'anti-ad.net'
          default-nameserver:
            - https://223.5.5.5/dns-query
            - https://1.12.12.12/dns-query
          nameserver:
            - https://dns.alidns.com/dns-query
            - https://doh.pub/dns-query
          nameserver-policy:
            'rule-set:microsoft-cn,apple-cn,google-cn,games-cn': [https://doh.pub/dns-query, https://dns.alidns.com/dns-query]
            'rule-set:cn,private': [https://doh.pub/dns-query, https://dns.alidns.com/dns-query]
            'rule-set:proxy': ['https://dns.google/dns-query#🪜 代理域名', 'https://cloudflare-dns.com/dns-query#🪜 代理域名']
        EOF

    - name: Commit and push
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add . && git commit -m "更新于 ${update_version}" || exit 0
        git push -f

    - name: Purge jsDelivr CDN
      run: |
        cd ./fake-ip-config/ || exit 1
        for file in $(ls); do
          curl -i "https://purge.jsdelivr.net/gh/${{ github.repository }}@main/fake-ip-config/${file}"
        done
